title: Lucino Garcia # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Scientist</b> <br>
  <b>Biomedical Engineer</b>
  
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
